import React, { useEffect, useRef, useState } from 'react'
import { HashRouter, Link, NavLink, Route, Routes, useNavigate, useLocation } from 'react-router-dom'
import { ArrowRight, TrainFront } from 'lucide-react'

const passengerNav = [['Overview', 'overview'], ['Stable ETA', 'stable-eta'], ['Delay Explanation', 'delay-explanation'], ['Connection Risk', 'connection-risk']]
const authorityNav = [['Overview', ''], ['Delay Propagation', 'delay-propagation'], ['Delay & Recovery', 'delay-recovery'], ['Stable ETA', 'stable-eta']]

export function EmptyState({ title = 'No prediction data available', detail = 'Waiting for backend data' }) { return <div className="empty-state"><span className="empty-mark">—</span><strong>{title}</strong><span>{detail}</span></div> }
function scrollToSection(id) { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }
function Header({ authority = false, active = 'overview' }) { const nav = authority ? authorityNav : passengerNav; const base = authority ? '/authority-dashboard' : '/passenger-dashboard'; return <header className="dashboard-header passenger-nav"><Link className="brand" to={base}><span className="brand-mark"><TrainFront size={16} /></span><span>Railway.in</span></Link><nav>{nav.map(([label, id], index) => authority ? <NavLink key={label} end={!id} to={`${base}${id ? `/${id}` : ''}`} className={({ isActive }) => isActive ? 'active' : ''}>{label}</NavLink> : <a key={label} className={active === id ? 'active' : ''} href={`#${id}`} onClick={event => { event.preventDefault(); scrollToSection(id) }}>{label}</a>)}</nav><Link className="exit-link" to={authority ? '/authority-login' : '/'}>{authority ? 'Sign out' : 'Back to home'}</Link></header> }
function RailwayMap() { return <section className="map-panel"><div className="section-kicker">Live context</div><h2>Railway map</h2><div className="map-empty"><div className="map-grid" /><div className="map-copy"><span className="map-line" /><strong>Waiting for live railway data</strong><span>Map connections will appear when a backend source is available.</span></div></div></section> }
function FieldList({ fields }) { return <div className="eta-list">{fields.map(label => <div className="eta-row" key={label}><span>{label}</span><b>—</b></div>)}</div> }
function StationEtaPanel() { return <section className="eta-panel"><div className="section-kicker">Station-wise ETA</div><h2>Upcoming movement</h2><FieldList fields={['Upcoming station', 'Predicted arrival', 'ETA range', 'Delay', 'Reliability']} /></section> }
function FeatureCard({ title, description, label, href }) { const target = href.replace('#', ''); return <a className="feature-card" href={href} onClick={event => { event.preventDefault(); scrollToSection(target) }}><span className="section-kicker">Passenger feature</span><h3>{title}</h3><p>{description}</p><span className="feature-link">{label} <ArrowRight size={16} /></span></a> }
function FeatureSections() { return <><section id="stable-eta" className="passenger-section"><span className="section-kicker">Passenger feature</span><h2>Stable Passenger ETA</h2><p className="feature-lede">Prevents unnecessary minute-by-minute ETA fluctuations and shows only meaningful changes.</p><div className="feature-panel"><FieldList fields={['Current ETA', 'ETA Range', 'Previous ETA', 'Change', 'Stability', 'Reliability']} /></div></section><section id="delay-explanation" className="passenger-section"><span className="section-kicker">Passenger feature</span><h2>Why is my train delayed?</h2><p className="feature-lede">Provides passengers with clear, plain-language reasons for delays and expected recovery.</p><div className="feature-panel"><FieldList fields={['Current Delay', 'Why is my train delayed?', 'Expected Recovery', 'Current Status']} /><div className="plain-language"><strong>Waiting for prediction</strong><span>Simple delay context will appear when backend data is available.</span></div></div></section><section id="connection-risk" className="passenger-section"><span className="section-kicker">Passenger feature</span><h2>Connection Risk Alerts</h2><p className="feature-lede">Warns passengers when predicted delays may affect connecting trains or onward journeys.</p><div className="feature-panel"><FieldList fields={['Connecting Journey', 'Predicted Arrival', 'Connection Time', 'Risk', 'Recommendation']} /></div></section></> }
function PassengerDashboard() { const [active, setActive] = useState('overview'); useEffect(() => { const sections = ['overview', 'stable-eta', 'delay-explanation', 'connection-risk'].map(id => document.getElementById(id)).filter(Boolean); const observer = new IntersectionObserver(entries => { const visible = entries.filter(entry => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActive(visible.target.id) }, { rootMargin: '-20% 0px -55% 0px', threshold: [0.1, 0.4, 0.8] }); sections.forEach(section => observer.observe(section)); return () => observer.disconnect() }, []); return <><Header active={active} /><main className="passenger-dashboard"><section id="overview" className="passenger-overview"><div className="dashboard-title"><div><span className="section-kicker">Passenger overview</span><h1>Your journey, made clearer.</h1></div><span className="data-badge">Backend connection pending</span></div><div className="passenger-overview-grid"><RailwayMap /><StationEtaPanel /></div></section><div className="feature-cards"><FeatureCard title="Stable Passenger ETA" description="See meaningful ETA changes without constant minute-by-minute fluctuations." label="View Stable ETA" href="#stable-eta" /><FeatureCard title="Simple Delay Explanation" description="Understand why your train is delayed and whether it is expected to recover." label="View Delay Explanation" href="#delay-explanation" /><FeatureCard title="Connection Risk" description="See whether your predicted arrival may affect a connecting train." label="Check Connection Risk" href="#connection-risk" /></div><FeatureSections /><Link className="back-link dashboard-back" to="/">← Back to Home</Link></main></> }
function Home() { const [query, setQuery] = useState(''); const nav = useNavigate(); return <><header className="home-header"><div className="home-brand-card"><Link className="brand" to="/"><span className="brand-mark"><TrainFront size={16} /></span><span>Railway.in</span></Link></div><div className="home-authority-card"><Link className="authority-link" to="/authority-login">Authority Login</Link></div></header><main className="home"><div className="home-copy"><h1>Beyond live status.<br /><em>See what happens next.</em></h1><p>Dynamic ETAs for every stop ahead.</p><form className="search-bar" onSubmit={e => { e.preventDefault(); nav(`/passenger-dashboard?train=${encodeURIComponent(query)}`) }}><input aria-label="Train number or train name" value={query} onChange={e => setQuery(e.target.value)} placeholder="Enter train number or train name" /><button type="submit">Search train →</button></form></div></main></> }
function Login() { const nav = useNavigate(); return <><header className="home-header"><Link className="brand" to="/"><span className="brand-mark"><TrainFront size={16} /></span><span>Railway.in</span></Link></header><main className="login-page"><form onSubmit={e => { e.preventDefault(); nav('/authority-dashboard') }}><span className="section-kicker">Authority access</span><h1>Welcome back.</h1><label>Work email<input type="email" required placeholder="Enter your work email" /></label><label>Password<input type="password" required placeholder="Enter your password" /></label><button type="submit">Continue →</button><Link className="back-link" to="/">← Back to home</Link></form></main></> }
function AuthorityPage({ type }) { const configs = { propagation: ['Network-Aware Delay Propagation', 'Prediction workspace for network delay movement.'], recovery: ['Explainable Delay & Recovery Forecast', 'Prediction workspace for delay source and recovery.'], stable: ['Confidence-Aware Stable ETA', 'Prediction workspace for stable passenger ETA.'] }; const config = configs[type]; return <><Header authority /><main className="feature-page"><Link className="back-link" to="/authority-dashboard">← Back to Authority Dashboard</Link><span className="section-kicker">Authority prediction</span><h1>{config[0]}</h1><p className="feature-lede">{config[1]}</p><EmptyState title="No prediction data available" /></main></> }
function AuthorityDashboard() { return <><Header authority /><main className="dashboard"><div className="dashboard-title"><div><span className="section-kicker">Railway authority</span><h1>Operational prediction workspace</h1></div><span className="data-badge">Backend connection pending</span></div><div className="dashboard-grid"><RailwayMap /><StationEtaPanel /></div></main></> }
export default function RailwayApp() { return <HashRouter><Routes><Route path="/" element={<Home />} /><Route path="/authority-login" element={<Login />} /><Route path="/passenger-dashboard" element={<PassengerDashboard />} /><Route path="/authority-dashboard" element={<AuthorityDashboard />} /><Route path="/authority-dashboard/delay-propagation" element={<AuthorityPage type="propagation" />} /><Route path="/authority-dashboard/delay-recovery" element={<AuthorityPage type="recovery" />} /><Route path="/authority-dashboard/stable-eta" element={<AuthorityPage type="stable" />} /></Routes></HashRouter> }
